server:
  port: 81
eureka:
  client:
    # false表示不向注册中心注册自己，只有客户端才需要注册
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
winston:
  config:
    ruletime: 5
    peoviderurl: http://OPTIMIZECLOUD-CONFIG-PROVIDER-CLIENT